
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\023\000\002\002\004\000\002\002\006\000\002\003" +
    "\004\000\002\004\004\000\002\005\012\000\002\005\011" +
    "\000\002\013\005\000\002\013\003\000\002\014\004\000" +
    "\002\014\003\000\002\015\014\000\002\010\004\000\002" +
    "\010\003\000\002\007\012\000\002\007\011\000\002\011" +
    "\004\000\002\011\003\000\002\012\011\000\002\012\012" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\101\000\004\004\005\001\002\000\004\005\011\001" +
    "\002\000\004\023\010\001\002\000\004\002\007\001\002" +
    "\000\004\002\001\001\002\000\004\005\uffff\001\002\000" +
    "\004\006\055\001\002\000\004\015\013\001\002\000\006" +
    "\016\021\022\020\001\002\000\004\015\ufff5\001\002\000" +
    "\004\015\016\001\002\000\010\002\000\016\021\022\020" +
    "\001\002\000\004\015\ufff6\001\002\000\004\027\047\001" +
    "\002\000\004\027\022\001\002\000\004\027\023\001\002" +
    "\000\004\014\024\001\002\000\004\030\025\001\002\000" +
    "\004\017\026\001\002\000\004\032\027\001\002\000\004" +
    "\020\033\001\002\000\004\015\ufff4\001\002\000\006\015" +
    "\ufff1\032\027\001\002\000\004\015\ufff2\001\002\000\006" +
    "\021\035\024\034\001\002\000\004\032\043\001\002\000" +
    "\004\024\036\001\002\000\004\032\037\001\002\000\004" +
    "\014\040\001\002\000\004\024\041\001\002\000\004\032" +
    "\042\001\002\000\006\015\uffef\032\uffef\001\002\000\004" +
    "\014\044\001\002\000\004\024\045\001\002\000\004\032" +
    "\046\001\002\000\006\015\ufff0\032\ufff0\001\002\000\004" +
    "\027\050\001\002\000\004\014\051\001\002\000\004\030" +
    "\052\001\002\000\004\032\027\001\002\000\004\015\ufff3" +
    "\001\002\000\004\015\ufffe\001\002\000\004\031\056\001" +
    "\002\000\004\007\057\001\002\000\004\010\060\001\002" +
    "\000\004\024\062\001\002\000\004\011\065\001\002\000" +
    "\006\011\ufffa\012\063\001\002\000\004\024\062\001\002" +
    "\000\004\011\ufffb\001\002\000\004\013\067\001\002\000" +
    "\010\006\ufff8\013\067\015\ufff8\001\002\000\004\032\072" +
    "\001\002\000\006\006\055\015\ufffc\001\002\000\004\015" +
    "\ufffd\001\002\000\004\026\073\001\002\000\004\014\074" +
    "\001\002\000\004\031\075\001\002\000\004\024\076\001" +
    "\002\000\004\032\077\001\002\000\004\014\100\001\002" +
    "\000\004\024\101\001\002\000\004\032\102\001\002\000" +
    "\010\006\ufff7\013\ufff7\015\ufff7\001\002\000\006\006\ufff9" +
    "\015\ufff9\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\101\000\006\002\005\003\003\001\001\000\004\004" +
    "\011\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\005\053\001\001\000" +
    "\006\007\013\010\014\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\016\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\011\027\012\030\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\011\031\012\030\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\011\052\012\030\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\013\060\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\013\063\001\001\000\002\001\001\000\006" +
    "\014\067\015\065\001\001\000\006\014\102\015\065\001" +
    "\001\000\002\001\001\000\004\005\070\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    class Partido {
        int nro;
        String fecha;
        String estadio;
        String equipoLocal;
        int golesLocal;
        String equipoVisitante;
        int golesVisitante;
    }


    class Participante {
        String nombre;
        String apellido;
        String mail;
        Map<Integer, String> pronosticos = new HashMap<>();
        List<Integer> marcados = new ArrayList<>();
        int puntaje;
    }

    Map<Integer, Partido> partidos = new HashMap<>();
    Map<String, List<String>> series = new HashMap<>();
    List<Participante> participantes = new ArrayList<>();


    // Reportes de errores

    public void report_error(String message, Object info) {
        StringBuffer m = new StringBuffer("⚠️ ERROR SINTACTICO");
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {
                m.append(" en línea "+(s.left+1));
                if (s.right >= 0)
                    m.append(", columna "+(s.right+1));
            }
        }
        m.append(" : "+message);
        System.err.println(m);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= campeonato fixture participantes SEPARADOR 
            {
              Object RESULT =null;
		
            System.out.println("\n✅ Analisis completado correctamente.");

            System.out.println("\n\n🏅 Ranking por puntos:");
            Collections.sort(participantes, (p1, p2) -> Integer.compare(p2.puntaje, p1.puntaje));

            for (Participante part: participantes) {
                System.out.println(
                    "👤 Participante: " + part.nombre + " " + part.apellido +
                    " | Puntaje: " + part.puntaje
                );
            }


            System.out.println("\n\n📊 Estadisticas del campeonato:");

            int promedioGoles = 0;
            for (Partido part : partidos.values()) {
                promedioGoles += part.golesLocal + part.golesVisitante;
            }
            promedioGoles /= partidos.size();

            System.out.println("Promedio de goles por partido: " + promedioGoles);
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // campeonato ::= CAMPEONATO TORNEO 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            System.out.println("🏆 Se esta jugando: " + t);
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("campeonato",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // fixture ::= FIXTURE fixture_partidos 
            {
              Object RESULT =null;
		
            System.out.println("\n✅ Se completo el fixture.\n");

            if (series.size() != 4 && series.size() != 8 && series.size() != 12) {
                report_error("El campeonato debe tener 4, 8 o 12 series. Se encontraron: " + series.size(), null);
                throw new RuntimeException("Parse abortado por cantidad inválida de series.");
            }
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("fixture",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // fixture_partidos ::= SERIE QSTRING PRE_EQUIPOS CORCHETE_IZQ equipos CORCHETE_DER partidos fixture_partidos 
            {
              Object RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		String g = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int eqleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int eqright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		List<String> eq = (List<String>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int partleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int partright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<Partido> part = (List<Partido>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object resto = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                series.put(g, eq);

                if (eq.size() > 4){
                    report_error("La serie " + g + " no tiene 4 equipos exactamente.", null);
                    throw new RuntimeException("Parse abortado por cantidad inválida de equipos dentro de una serie.");
                }

                System.out.println("\n📦 Serie agregada: " + g + " Equipos: " + String.join(", ", eq) + ".");

                for(Partido p: part) {
                    System.out.println(
                        "⚽ Partido agregado: N°" + p.nro +
                        " | " + p.equipoLocal + " " + p.golesLocal + " - " + p.golesVisitante + " " + p.equipoVisitante +
                        " | Fecha: " + p.fecha +
                        " | Estadio: " + p.estadio
                    );
                }
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("fixture_partidos",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // fixture_partidos ::= SERIE QSTRING PRE_EQUIPOS CORCHETE_IZQ equipos CORCHETE_DER partidos 
            {
              Object RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String g = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int eqleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eqright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		List<String> eq = (List<String>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int partleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int partright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		List<Partido> part = (List<Partido>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                series.put(g, eq);

                if (eq.size() > 4){
                    report_error("La serie " + g + " no tiene 4 equipos exactamente.", null);
                    throw new RuntimeException("Parse abortado por cantidad inválida de equipos dentro de una serie.");
                }
                    
                System.out.println("\n📦 Serie agregada: " + g + " Equipos: " + String.join(", ", eq) + ".");

                for(Partido p: part) {
                    System.out.println(
                        "⚽ Partido agregado: N°" + p.nro +
                        " | " + p.equipoLocal + " " + p.golesLocal + " - " + p.golesVisitante + " " + p.equipoVisitante +
                        " | Fecha: " + p.fecha +
                        " | Estadio: " + p.estadio
                    );
                }
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("fixture_partidos",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // equipos ::= EQUIPO COMA equipos 
            {
              List<String> RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		List<String> resto = (List<String>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                List<String> lista = new ArrayList<>();
                lista.add(n);
                lista.addAll(resto);

                RESULT = lista;
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("equipos",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // equipos ::= EQUIPO 
            {
              List<String> RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                List<String> lista = new ArrayList<>();
                lista.add(n);

                RESULT = lista;
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("equipos",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // partidos ::= partido partidos 
            {
              List<Partido> RESULT =null;
		int partleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int partright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Partido part = (Partido)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		List<Partido> resto = (List<Partido>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                List<Partido> result = (List<Partido>) resto;
                result.add(part);

                RESULT = result;
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("partidos",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // partidos ::= partido 
            {
              List<Partido> RESULT =null;
		int partleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int partright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Partido part = (Partido)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                List<Partido> result = new ArrayList<>();
                result.add(part);

                RESULT = result;
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("partidos",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // partido ::= NRO_PARTIDO NUMERO FECHA GUION QSTRING EQUIPO NUMERO GUION EQUIPO NUMERO 
            {
              Partido RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		String f = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int locleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int locright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String loc = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int g1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int g1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer g1 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int visleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int visright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String vis = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int g2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int g2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer g2 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            Partido result = new Partido();
            result.nro = n;
            result.fecha = f;
            result.estadio = e;
            result.equipoLocal = loc;
            result.golesLocal = g1;
            result.equipoVisitante = vis;
            result.golesVisitante = g2;

            partidos.put(n, result);

            RESULT = result;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("partido",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // participantes ::= participantes participante 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("participantes",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // participantes ::= participante 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("participantes",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // participante ::= SEPARADOR PRE_PARTICIPANTE NOMBRE NOMBRE GUION EMAIL PRONOSTICOS pronosticos 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int mailleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int mailright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String mail = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int pronleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pronright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Map<String,Object> pron = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            Participante p = new Participante();
            p.nombre = n;
            p.apellido = a;
            p.mail = mail;
            p.pronosticos.putAll((Map<Integer,String>) pron.get("ganadores"));
            p.marcados.addAll((List<Integer>) pron.get("marcados"));
            p.puntaje += (int) pron.get("puntaje");

            if (p.marcados.size() > 4) {
                report_error("El participante " + n + " tiene más de 4 pronósticos marcados con (X)", null);
                throw new RuntimeException("Parse abortado por cantidad inválida de pronosticos marcados con (X).");
            }

            participantes.add(p);
            
            System.out.println(
                    "👤 Participante agregado: " + n + " " + a + 
                    " Pronósticos: " + p.pronosticos.size() + 
                    " | Marcados(X): " + p.marcados.size() + 
                    " | Email: " + mail +
                    " | Puntaje: " + p.puntaje
            );
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("participante",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // participante ::= SEPARADOR JUEGO NOMBRE NOMBRE GUION EMAIL pronosticos 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int mailleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int mailright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String mail = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int pronleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pronright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Map<String,Object> pron = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            Participante p = new Participante();
            p.nombre = n;
            p.apellido = a;
            p.mail = mail;
            p.pronosticos.putAll((Map<Integer,String>) pron.get("ganadores"));
            p.marcados.addAll((List<Integer>) pron.get("marcados"));
            p.puntaje += (int) pron.get("puntaje");

            if (p.marcados.size() > 4) {
                report_error("El participante " + n + " tiene más de 4 pronósticos marcados con (X)", null);
                throw new RuntimeException("Parse abortado por cantidad inválida de pronosticos marcados con (X).");
            }

            participantes.add(p);
            
            System.out.println(
                    "👤 Participante agregado: " + n + " " + a + 
                    " Pronósticos: " + p.pronosticos.size() + 
                    " | Marcados(X): " + p.marcados.size() + 
                    " | Email: " + mail +
                    " | Puntaje: " + p.puntaje
            );
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("participante",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // pronosticos ::= pronostico pronosticos 
            {
              Map<String,Object> RESULT =null;
		int pronleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pronright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Map<String,Object> pron = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Map<String,Object> resto = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            Map<String, Object> result = new HashMap<>();

            Map<Integer, String> ganadores = (Map<Integer, String>) resto.get("ganadores");
            List<Integer> marcados = (List<Integer>) resto.get("marcados");
            int puntaje = (int) resto.get("puntaje");

            Integer partido = (Integer) pron.get("partido");
            String ganador = (String) pron.get("ganador");
            boolean marcado = (boolean) pron.get("marcado");
            puntaje += (int) pron.get("puntaje");

            if (ganadores.containsKey(partido)) {
                report_error("Se detecto dos pronosticos para el mismo partido: " + partido + ".", null);
                throw new RuntimeException("Parse abortado por pronosticos inválidos dentro de un participante.");
            }

            ganadores.put(partido, ganador);
            if (marcado) marcados.add(partido);

            result.put("ganadores", ganadores);
            result.put("marcados", marcados);
            result.put("puntaje", puntaje);

            RESULT = result;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pronosticos",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // pronosticos ::= pronostico 
            {
              Map<String,Object> RESULT =null;
		int pronleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pronright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Map<String,Object> pron = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            Map<String,Object> result = new HashMap<>();

            Map<Integer, String> ganadores = new HashMap<Integer,String>();
            List<Integer> marcados = new ArrayList<>();
            int puntaje = 0;

            Integer partido = (Integer) pron.get("partido");
            String ganador = (String) pron.get("ganador");
            boolean marcado = (boolean) pron.get("marcado");
            puntaje += (int) pron.get("puntaje");

            if (ganadores.containsKey(partido)) {
                report_error("Se detecto dos pronosticos para el mismo partido: " + partido + ".", null);
                throw new RuntimeException("Parse abortado por pronosticos inválidos dentro de un participante.");
            }

            ganadores.put(partido, ganador);
            if (marcado) marcados.add(partido);

            result.put("ganadores", ganadores);
            result.put("marcados", marcados);
            result.put("puntaje", puntaje);

            RESULT = result;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pronosticos",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // pronostico ::= NUMERO DOSPUNTOS EQUIPO NUMERO GUION EQUIPO NUMERO 
            {
              Map<String,Object> RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Integer p = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int g1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int g1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer g1 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int g2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int g2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer g2 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            Map<String, Object> result = new HashMap<>();
            String prediccionGanador = "";

            Partido part = partidos.get(p);

            if (part == null) {
                report_error("Se detecto un pronosticos para el partido: " + p + ", pero el mismo no existe.", null);
                throw new RuntimeException("Parse abortado por pronosticos inválidos dentro de un participante.");
            }

            if (!part.equipoLocal.equals(e1) && !part.equipoVisitante.equals(e2)){
                report_error("Se detecto un pronosticos para el partido: " + p + ", pero sus equipos son incorrectos.", null);
                throw new RuntimeException("Parse abortado por pronosticos inválidos dentro de un participante.");
            }

            if (g1 > g2) prediccionGanador = e1;
            else if (g2 > g1) prediccionGanador = e2;

            int puntaje = 0;

            boolean isEmpate = part.golesLocal == part.golesVisitante;
            String ganadorPartido = null;

            if (!isEmpate)
                ganadorPartido = part.golesLocal > part.golesVisitante ? part.equipoLocal : part.equipoVisitante;

            if (prediccionGanador.equals(ganadorPartido))
                puntaje += 2;

            if (part.golesLocal == g1 || part.golesVisitante == g2)
                puntaje += 1;

            if (part.golesLocal == g1 && part.golesVisitante == g2)
                puntaje += 1;
            
            result.put("partido", p);
            result.put("ganador", prediccionGanador);
            result.put("marcado", false);
            result.put("puntaje", puntaje);

            RESULT = result;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pronostico",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // pronostico ::= NUMERO DOSPUNTOS MARCA EQUIPO NUMERO GUION EQUIPO NUMERO 
            {
              Map<String,Object> RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		Integer p = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int g1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int g1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer g1 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int g2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int g2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer g2 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            Map<String, Object> result = new HashMap<>();
            String prediccionGanador = "";

            Partido part = partidos.get(p);

            if (part == null) {
                report_error("Se detecto un pronosticos para el partido: " + p + ", pero el mismo no existe.", null);
                throw new RuntimeException("Parse abortado por pronosticos inválidos dentro de un participante.");
            }

            if (!part.equipoLocal.equals(e1) && !part.equipoVisitante.equals(e2)){
                report_error("Se detecto un pronosticos para el partido: " + p + ", pero sus equipos son incorrectos.", null);
                throw new RuntimeException("Parse abortado por pronosticos inválidos dentro de un participante.");
            }

            if (g1 > g2) prediccionGanador = e1;
            else if (g2 > g1) prediccionGanador = e2;

            int puntaje = 0;

            boolean isEmpate = part.golesLocal == part.golesVisitante;
            String ganadorPartido = null;

            if (!isEmpate)
                ganadorPartido = part.golesLocal > part.golesVisitante ? part.equipoLocal : part.equipoVisitante;

            if (prediccionGanador.equals(ganadorPartido))
                puntaje += 2;
                
            if (part.golesLocal == g1 || part.golesVisitante == g2)
                puntaje += 1;

            if (part.golesLocal == g1 && part.golesVisitante == g2)
                puntaje += 1;

            puntaje = puntaje * 2;
            
            result.put("partido", p);
            result.put("ganador", prediccionGanador);
            result.put("marcado", true);
            result.put("puntaje", puntaje);

            RESULT = result;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pronostico",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
