import java_cup.runtime.*;
import java.util.*;
import java.io.*;

parser code {:
    class Partido {
        int nro;
        String fecha;
        String estadio;
        String equipoLocal;
        int golesLocal;
        String equipoVisitante;
        int golesVisitante;
    }


    class Participante {
        String nombre;
        String apellido;
        String mail;
        Map<Integer, String> pronosticos = new HashMap<>();
        List<Integer> marcados = new ArrayList<>();
    }


    List<Partido> partidos = new ArrayList<>();
    Map<String, List<String>> series = new HashMap<>();
    List<Participante> participantes = new ArrayList<>();


    // Reportes de errores

    public void report_error(String message, Object info) {
        StringBuffer m = new StringBuffer("Error");
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {
                m.append(" en línea "+(s.left+1));
                if (s.right >= 0)
                    m.append(", columna "+(s.right+1));
            }
        }
        m.append(" : "+message);
        System.err.println(m);
    }
:};


terminal CAMPEONATO, FIXTURE, SERIE, PRE_GRUPO, PRE_EQUIPOS,
         CORCHETE_IZQ, CORCHETE_DER, COMA, NRO_PARTIDO, GUION,
         SEPARADOR, PRE_PARTICIPANTE, PRONOSTICOS, DOSPUNTOS, MARCA;

terminal String TORNEO, LETRA_GRUPO, EQUIPO, ESTADIO, HORA, FECHA, NOMBRE, EMAIL, QSTRING;
terminal Integer NUMERO, RESULTADO;


non terminal Object inicio, campeonato, fixture, fixture_partidos, partido, serie, participante, participantes, partidos;
non terminal Map<String, Object> pronosticos, pronostico;
non terminal List<String> equipos;


start with inicio;


inicio ::= campeonato fixture participantes
        {:
            System.out.println("✅ Analisis completado correctamente.");
        :};


campeonato ::= CAMPEONATO TORNEO:t
        {:
            System.out.println("🏆 Se esta jugando: " + t);
        :};


fixture::= 
            FIXTURE 
            fixture_partidos
        {:
            System.out.println("✅ Se completo el fixture.");
        :};


fixture_partidos::= 
            SERIE QSTRING:g
            PRE_EQUIPOS CORCHETE_IZQ equipos:eq CORCHETE_DER
            partidos
            fixture_partidos:resto
            {:
                series.put(g, eq);
                System.out.println("📦 Serie agregada: " + g + " Equipos: " + String.join(", ", eq) + ".");
            :}
            |
            SERIE QSTRING:g
            PRE_EQUIPOS CORCHETE_IZQ equipos:eq CORCHETE_DER
            partidos 
            {:
                series.put(g, eq);
            :};

equipos ::= EQUIPO:n COMA equipos:resto
            {:
                List<String> lista = new ArrayList<>();
                lista.add(n);
                lista.addAll(resto);

                RESULT = lista;
            :} 
            | EQUIPO:n 
            {:
                List<String> lista = new ArrayList<>();
                lista.add(n);

                RESULT = lista;
            :};

partidos ::= partido 
             partidos 
             |
             partido;


partido ::= NRO_PARTIDO NUMERO:n
            FECHA:f GUION QSTRING:e
            EQUIPO:loc NUMERO:g1 GUION EQUIPO:vis NUMERO:g2
        {:
            Partido p = new Partido();
            p.nro = n;
            p.fecha = f;
            p.estadio = e;
            p.equipoLocal = loc;
            p.golesLocal = g1;
            p.equipoVisitante = vis;
            p.golesVisitante = g2;
            partidos.add(p);

            System.out.println(
                "⚽ Partido agregado: N°" + n +
                " | " + loc + " " + g1 + " - " + g2 + " " + vis +
                " | Fecha: " + f +
                " | Estadio: " + e
            );
        :};


participantes ::= participantes participante|participante;


participante::= SEPARADOR PRE_PARTICIPANTE NOMBRE:n NOMBRE:a GUION EMAIL:mail
                PRONOSTICOS 
                pronosticos:pron
        {:
            Participante p = new Participante();
            p.nombre = n;
            p.apellido = a;
            p.mail = mail;
            p.pronosticos.putAll((Map<Integer,String>) pron.get("ganadores"));
            p.marcados.addAll((List<Integer>) pron.get("marcados"));

            if (p.marcados.size() > 4)
                report_error("El participante " + n + " tiene más de 4 pronósticos marcados con (X)", null);

            participantes.add(p);
            
            System.out.println(
                    "👤 Participante agregado: " + n + " " + a + 
                    " Pronósticos: " + p.pronosticos.size() + 
                    " | Marcados(X): " + p.marcados.size() + 
                    " | Email: " + mail
            );
        :};


pronosticos ::= pronostico:pron pronosticos:resto
        {:
            Map<String, Object> result = new HashMap<>();

            Map<Integer, String> ganadores = (Map<Integer, String>) resto.get("ganadores");
            List<Integer> marcados = (List<Integer>) resto.get("marcados");

            Integer partido = (Integer) pron.get("partido");
            String ganador = (String) pron.get("ganador");
            boolean marcado = (boolean) pron.get("marcado");

            ganadores.put(partido, ganador);
            if (marcado) marcados.add(partido);

            result.put("ganadores", ganadores);
            result.put("marcados", marcados);

            RESULT = result;
        :}
        | pronostico:pron 
        {:
            Map<String,Object> result = new HashMap<>();

            Map<Integer, String> ganadores = new HashMap<Integer,String>();
            List<Integer> marcados = new ArrayList<>();

            Integer partido = (Integer) pron.get("partido");
            String ganador = (String) pron.get("ganador");
            boolean marcado = (boolean) pron.get("marcado");

            ganadores.put(partido, ganador);
            if (marcado) marcados.add(partido);

            result.put("ganadores", ganadores);
            result.put("marcados", marcados);

            RESULT = result;
        :};


pronostico ::= NUMERO:p DOSPUNTOS EQUIPO:e1 NUMERO:g1 GUION EQUIPO:e2 NUMERO:g2
        {:
            Map<String, Object> result = new HashMap<>();
            String ganador = "";

            if (g1 > g2) ganador = e1;
            else if (g2 > g1) ganador = e2;
            
            result.put("partido", p);
            result.put("ganador", ganador);
            result.put("marcado", false);

            RESULT = result;
        :}
        | NUMERO:p DOSPUNTOS MARCA EQUIPO:e1 NUMERO:g1 GUION EQUIPO:e2 NUMERO:g2
        {:
            Map<String, Object> result = new HashMap<>();
            String ganador = "";

            if (g1 > g2) ganador = e1;
            else if (g2 > g1) ganador = e2;
            
            result.put("partido", p);
            result.put("ganador", ganador);
            result.put("marcado", true);

            RESULT = result;
        :};