// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: pronostico.flex

import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\2\22\0\1\5"+
    "\1\0\1\6\2\0\1\7\2\0\1\10\1\11\1\12"+
    "\1\7\1\13\1\14\1\15\1\16\2\17\1\20\1\21"+
    "\2\22\4\23\1\24\1\25\4\0\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\2\35\1\36\1\37\2\35"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\35"+
    "\1\47\2\35\1\50\2\35\1\51\1\0\1\52\1\0"+
    "\1\7\1\0\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\60\1\65\1\66\1\67"+
    "\1\70\1\71\1\72\1\73\1\74\1\75\1\76\1\77"+
    "\1\60\1\100\1\101\1\102\1\0\1\103\10\0\1\3"+
    "\133\0\1\104\7\0\1\105\3\0\1\106\3\0\1\107"+
    "\1\0\1\110\6\0\1\111\u012d\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\3\2\4\1\1\3\1\4\4\5\1\6"+
    "\16\7\1\10\1\11\1\0\1\12\5\0\3\5\17\7"+
    "\1\0\5\7\1\0\3\7\2\0\1\13\3\0\1\5"+
    "\2\0\23\7\1\0\2\7\1\0\4\7\1\0\3\7"+
    "\15\0\1\5\2\0\22\7\1\0\1\7\1\0\2\7"+
    "\1\0\4\7\1\0\2\7\1\0\1\14\16\0\1\5"+
    "\1\15\1\0\3\7\1\0\3\7\1\16\2\7\1\0"+
    "\3\7\1\16\1\7\1\0\1\7\1\0\1\7\1\0"+
    "\1\17\2\7\7\0\1\7\1\0\5\7\1\20\2\7"+
    "\1\0\1\7\1\0\1\7\7\0\1\7\1\0\3\7"+
    "\1\21\3\7\1\0\1\7\6\0\1\22\1\7\1\0"+
    "\1\23\1\0\2\7\7\0\1\7\1\0\1\7\5\0"+
    "\1\22\1\24\1\0\1\7\6\0\1\7\5\0\1\7"+
    "\1\25\3\0\1\26\1\0\1\27\14\0\1\30\1\0"+
    "\1\31";

  private static int [] zzUnpackAction() {
    int [] result = new int[303];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\112\0\224\0\336\0\u0128\0\u0172\0\u01bc\0\u0206"+
    "\0\u0250\0\112\0\u01bc\0\u029a\0\u02e4\0\u032e\0\u0378\0\112"+
    "\0\u03c2\0\u040c\0\u0456\0\u04a0\0\u04ea\0\u0534\0\u057e\0\u05c8"+
    "\0\u0612\0\u065c\0\u06a6\0\u06f0\0\u073a\0\u0784\0\112\0\112"+
    "\0\u07ce\0\112\0\u0818\0\u01bc\0\u0862\0\u08ac\0\u08f6\0\u0940"+
    "\0\u098a\0\u09d4\0\u0a1e\0\u0a68\0\u0ab2\0\u0afc\0\u0b46\0\u0b90"+
    "\0\u0bda\0\u0c24\0\u0c6e\0\u0cb8\0\u0d02\0\u0d4c\0\u0d96\0\u0de0"+
    "\0\u0e2a\0\u0e74\0\u0ebe\0\u0f08\0\u0f52\0\u0f9c\0\u0fe6\0\u1030"+
    "\0\u107a\0\u10c4\0\u110e\0\u1158\0\u11a2\0\112\0\u11ec\0\u1236"+
    "\0\u1280\0\u12ca\0\u1314\0\u135e\0\u13a8\0\u13f2\0\u143c\0\u1486"+
    "\0\u14d0\0\u151a\0\u1564\0\u15ae\0\u15f8\0\u1642\0\u168c\0\u16d6"+
    "\0\u1720\0\u176a\0\u17b4\0\u17fe\0\u1848\0\u1892\0\u18dc\0\u1926"+
    "\0\u1970\0\u19ba\0\u1a04\0\u1a4e\0\u1a98\0\u1ae2\0\u1b2c\0\u1b76"+
    "\0\u1bc0\0\u1c0a\0\u1c54\0\u1c9e\0\u1ce8\0\u1d32\0\u1d7c\0\u1dc6"+
    "\0\u1e10\0\u1e5a\0\u1ea4\0\u1eee\0\u1f38\0\u1f82\0\u1fcc\0\u2016"+
    "\0\u2060\0\u20aa\0\u20f4\0\u213e\0\u2188\0\u21d2\0\u221c\0\u2266"+
    "\0\u22b0\0\u22fa\0\u2344\0\u238e\0\u23d8\0\u2422\0\u246c\0\u24b6"+
    "\0\u2500\0\u254a\0\u2594\0\u25de\0\u2628\0\u2672\0\u26bc\0\u2706"+
    "\0\u2750\0\u279a\0\u27e4\0\u282e\0\u2878\0\u28c2\0\u290c\0\u2956"+
    "\0\u29a0\0\u29ea\0\u2a34\0\u1ce8\0\u2a7e\0\u2ac8\0\u2b12\0\u2b5c"+
    "\0\u2ba6\0\u2bf0\0\u2c3a\0\u2c84\0\u2cce\0\u2d18\0\u2d62\0\u2dac"+
    "\0\u2df6\0\u2e40\0\u2e8a\0\112\0\u2ed4\0\u2f1e\0\u2f68\0\u2fb2"+
    "\0\u2ffc\0\u3046\0\u3090\0\u30da\0\u04a0\0\u3124\0\u316e\0\u31b8"+
    "\0\u3202\0\u324c\0\u3296\0\112\0\u32e0\0\u332a\0\u3374\0\u33be"+
    "\0\u3408\0\u3452\0\u01bc\0\u349c\0\u34e6\0\u3530\0\u357a\0\u35c4"+
    "\0\u360e\0\u3658\0\u36a2\0\u36ec\0\u3736\0\u3780\0\u37ca\0\u3814"+
    "\0\u385e\0\u38a8\0\u38f2\0\112\0\u393c\0\u3986\0\u39d0\0\u3a1a"+
    "\0\u3a64\0\u3aae\0\u3af8\0\u3b42\0\u3b8c\0\u3bd6\0\u3c20\0\u3c6a"+
    "\0\u3cb4\0\u3cfe\0\u3d48\0\u3d92\0\u3ddc\0\u3e26\0\u04a0\0\u3e70"+
    "\0\u3eba\0\u3f04\0\u3f4e\0\u3f98\0\u3fe2\0\u402c\0\u4076\0\u40c0"+
    "\0\u410a\0\u4154\0\112\0\u419e\0\u41e8\0\112\0\u4232\0\u427c"+
    "\0\u42c6\0\u4310\0\u435a\0\u43a4\0\u43ee\0\u4438\0\u4482\0\u44cc"+
    "\0\u4516\0\u4560\0\u45aa\0\u45f4\0\u463e\0\u4688\0\u46d2\0\u471c"+
    "\0\u01bc\0\u04a0\0\u4766\0\u47b0\0\u47fa\0\u4844\0\u488e\0\u48d8"+
    "\0\u4922\0\u496c\0\u49b6\0\u4a00\0\u4a4a\0\u4a94\0\u4ade\0\u4b28"+
    "\0\u4b72\0\112\0\u4bbc\0\u4c06\0\u4c50\0\112\0\u4c9a\0\112"+
    "\0\u4ce4\0\u4d2e\0\u4d78\0\u4dc2\0\u4e0c\0\u4e56\0\u4ea0\0\u4eea"+
    "\0\u4f34\0\u4f7e\0\u4fc8\0\u5012\0\112\0\u505c\0\112";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[303];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\5\1\3\1\6\1\7"+
    "\1\10\1\2\1\11\1\12\1\13\1\7\1\2\1\14"+
    "\1\15\1\16\2\17\1\20\2\2\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\24\1\27\1\30\1\31\1\32"+
    "\1\24\1\33\1\34\1\24\1\35\1\36\1\24\1\37"+
    "\1\40\30\7\7\2\113\0\1\3\1\4\1\0\1\5"+
    "\1\3\105\0\2\4\2\0\1\4\105\0\1\5\2\0"+
    "\2\5\104\0\2\41\1\0\3\41\1\42\31\41\1\43"+
    "\51\41\7\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\30\44\57\0\1\46\55\0\1\47"+
    "\104\0\1\44\4\0\2\44\1\0\5\50\2\0\1\45"+
    "\22\44\2\0\30\44\16\0\1\44\4\0\2\44\1\0"+
    "\3\50\2\51\2\0\1\45\22\44\2\0\30\44\16\0"+
    "\1\44\4\0\2\44\1\0\5\51\2\0\1\45\22\44"+
    "\2\0\30\44\16\0\1\44\4\0\2\44\1\0\5\52"+
    "\2\0\1\45\22\44\2\0\30\44\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\12\24"+
    "\1\53\5\24\1\54\2\24\1\55\4\24\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\20\24\1\56\7\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\1\57\6\24\1\60"+
    "\5\24\1\61\12\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\30\24\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\17\24\1\62\1\24\1\63\6\24\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\10\24"+
    "\1\64\7\24\1\65\7\24\16\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\14\24\1\66"+
    "\5\24\1\67\5\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\1\70\22\24\1\71"+
    "\4\24\16\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\30\24\2\0\1\72\13\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\10\24\1\73\17\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\1\74\14\24\1\75"+
    "\2\24\1\76\7\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\1\77\27\24\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\4\44"+
    "\1\100\15\44\2\0\4\24\1\101\16\24\1\102\4\24"+
    "\16\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\20\24\1\103\7\24\7\0\2\41\1\0"+
    "\3\41\1\42\105\41\1\0\3\41\1\42\67\41\1\104"+
    "\13\41\27\0\22\105\2\0\30\105\20\0\1\106\112\0"+
    "\1\107\106\0\1\44\4\0\1\110\1\44\1\111\5\112"+
    "\1\113\1\0\1\45\22\44\2\0\30\44\1\114\15\0"+
    "\1\44\4\0\1\110\1\44\1\111\5\112\2\0\1\45"+
    "\22\44\2\0\30\44\1\114\15\0\1\44\4\0\2\44"+
    "\1\0\5\112\2\0\1\45\22\44\2\0\30\44\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\22\44"+
    "\2\0\4\24\1\115\23\24\16\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\6\24\1\116"+
    "\21\24\16\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\21\24\1\117\6\24\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\1\120\27\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\1\24\1\121\11\24\1\122"+
    "\1\123\13\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\10\24\1\124\17\24\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\22\44"+
    "\2\0\12\24\1\125\5\24\1\126\7\24\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\23\24\1\127\4\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\16\24\1\130\3\24"+
    "\1\131\5\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\25\24\1\132\2\24\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\22\44"+
    "\2\0\1\133\27\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\6\24\1\134\21\24"+
    "\16\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\1\135\27\24\16\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\16\24\1\136"+
    "\11\24\16\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\4\24\1\137\23\24\107\0\1\140"+
    "\20\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\6\24\1\141\21\24\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\20\24"+
    "\1\142\7\24\3\0\1\143\12\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\12\24\1\144"+
    "\5\24\1\145\7\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\15\24\1\146\12\24"+
    "\16\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\22\24\1\147\5\24\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\16\44\1\150\3\44"+
    "\2\0\30\44\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\14\24\1\151\13\24\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\22\44"+
    "\2\0\10\24\1\152\17\24\16\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\23\24\1\153"+
    "\4\24\7\0\2\41\1\0\3\41\1\42\60\41\1\154"+
    "\22\41\15\0\1\155\11\0\22\105\2\0\30\105\23\0"+
    "\1\156\104\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\1\157\2\44\1\160\1\161\1\162\2\44\1\163"+
    "\1\164\1\165\1\166\3\44\1\167\2\44\2\0\30\44"+
    "\26\0\1\170\101\0\1\44\4\0\2\44\1\0\5\171"+
    "\2\0\1\45\22\44\2\0\30\44\26\0\4\172\106\0"+
    "\1\173\101\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\13\24\1\174\14\24\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\4\24\1\175\23\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\22\24\1\176\5\24"+
    "\16\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\21\24\1\177\6\24\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\15\24"+
    "\1\200\12\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\4\24\1\201\11\24\1\202"+
    "\11\24\16\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\1\203\27\24\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\12\24"+
    "\1\204\15\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\15\24\1\205\12\24\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\22\44"+
    "\2\0\4\24\1\206\23\24\16\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\10\24\1\207"+
    "\17\24\16\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\1\210\27\24\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\1\211"+
    "\27\24\16\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\22\24\1\212\5\24\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\14\24\1\213\13\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\12\24\1\214\15\24"+
    "\16\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\12\24\1\215\15\24\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\30\24"+
    "\5\0\1\216\10\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\6\24\1\217\21\24\72\0"+
    "\1\220\35\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\4\24\1\221\23\24\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\22\24\1\222\5\24\103\0\1\223\24\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\15\24"+
    "\1\224\12\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\22\24\1\225\5\24\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\22\44"+
    "\2\0\14\24\1\226\13\24\16\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\1\227\27\24"+
    "\16\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\7\44\1\230\12\44\2\0\30\44\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\4\24"+
    "\1\231\23\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\27\24\1\206\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\6\24\1\232\21\24\7\0\2\41\1\0\3\41\1\42"+
    "\47\41\1\233\33\41\27\0\22\234\2\0\30\234\21\0"+
    "\1\235\106\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\1\44\1\236\4\44\1\237\21\44"+
    "\16\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\10\44\1\240\17\44\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\14\44"+
    "\1\241\13\44\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\4\44\1\242\23\44\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\22\44"+
    "\2\0\23\44\1\243\4\44\16\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\1\244\27\44"+
    "\16\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\15\44\1\245\12\44\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\2\44"+
    "\1\246\25\44\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\4\44\1\247\23\44\26\0"+
    "\5\250\75\0\1\44\4\0\1\251\1\44\1\252\5\253"+
    "\2\0\1\45\22\44\2\0\30\44\26\0\5\254\105\0"+
    "\5\255\75\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\1\256\27\24\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\14\24"+
    "\1\257\13\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\20\24\1\67\7\24\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\22\44"+
    "\2\0\10\24\1\260\17\24\14\0\1\261\1\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\30\24\16\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\20\24\1\262\7\24\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\4\24\1\263\23\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\3\24\1\264\24\24"+
    "\16\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\4\24\1\265\23\24\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\13\24"+
    "\1\266\14\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\1\265\27\24\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\16\24\1\267\11\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\30\24\4\0\1\270"+
    "\11\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\3\24\1\271\24\24\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\23\24"+
    "\1\272\4\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\2\24\1\215\25\24\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\22\44"+
    "\2\0\1\273\27\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\10\24\1\206\17\24"+
    "\76\0\1\274\31\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\15\24\1\275\12\24\64\0"+
    "\1\276\43\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\20\24\1\215\7\24\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\10\24\1\277\17\24\66\0\1\300\41\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\14\24"+
    "\1\301\13\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\23\24\1\231\4\24\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\22\44"+
    "\2\0\30\24\5\0\1\302\10\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\20\24\1\265"+
    "\7\24\16\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\4\44\1\303\15\44\2\0\30\44\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\6\24\1\304\21\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\23\24\1\305\4\24"+
    "\7\0\2\41\1\0\3\41\1\42\54\41\1\306\26\41"+
    "\14\0\1\307\104\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\20\44\1\310\7\44\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\22\44"+
    "\2\0\15\44\1\310\12\44\16\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\2\44\1\310"+
    "\25\44\16\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\4\44\1\310\23\44\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\1\44\1\310\26\44\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\12\44\1\310\1\44"+
    "\1\310\13\44\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\20\44\1\310\5\44\1\310"+
    "\1\44\16\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\24\44\1\310\3\44\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\22\44\1\310\5\44\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\16\44\1\310\11\44"+
    "\25\0\1\311\102\0\1\44\4\0\2\44\1\0\1\312"+
    "\4\44\2\0\1\45\22\44\2\0\30\44\26\0\1\313"+
    "\101\0\1\44\4\0\2\44\1\0\5\253\2\0\1\45"+
    "\22\44\2\0\30\44\112\0\1\314\15\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\14\24"+
    "\1\215\13\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\22\24\1\315\5\24\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\22\44"+
    "\2\0\12\24\1\265\15\24\43\0\1\316\64\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\30\24\6\0\1\216\7\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\15\24\1\317\12\24"+
    "\16\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\30\24\1\0\1\274\14\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\1\24"+
    "\1\215\26\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\15\24\1\320\12\24\62\0"+
    "\1\274\45\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\15\24\1\321\12\24\16\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\20\24\1\322\7\24\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\22\24\1\323\5\24"+
    "\16\0\1\44\4\0\2\44\1\0\5\44\1\324\1\0"+
    "\1\45\22\44\2\0\30\24\77\0\1\274\30\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\2\24\1\325\1\326\24\24\103\0\1\327\24\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\10\24\1\330\17\24\103\0\1\331\24\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\1\260"+
    "\27\24\16\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\1\332\27\24\7\0\2\41\1\0"+
    "\3\41\1\42\44\41\1\333\36\41\12\0\1\334\106\0"+
    "\1\44\4\0\1\335\1\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\30\44\26\0\5\336\75\0\1\44\4\0"+
    "\2\44\1\0\5\337\2\0\1\45\22\44\2\0\30\44"+
    "\26\0\5\340\105\0\5\341\75\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\10\24\1\342"+
    "\17\24\102\0\1\343\25\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\14\24\1\344\13\24"+
    "\16\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\21\24\1\345\6\24\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\21\24"+
    "\1\346\6\24\16\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\4\24\1\347\23\24\16\0"+
    "\1\44\4\0\2\44\1\0\5\44\2\0\1\45\22\44"+
    "\2\0\4\24\1\350\23\24\16\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\10\24\1\351"+
    "\17\24\16\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\15\24\1\352\12\24\14\0\1\353"+
    "\113\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\1\354\27\24\104\0\1\355\23\0\1\44"+
    "\4\0\2\44\1\0\5\44\2\0\1\45\22\44\2\0"+
    "\26\24\1\265\1\24\7\0\2\41\1\0\3\41\1\42"+
    "\56\41\1\356\24\41\14\0\1\357\104\0\1\44\4\0"+
    "\2\44\1\0\5\360\2\0\1\45\22\44\2\0\30\44"+
    "\26\0\5\314\75\0\1\44\4\0\1\361\1\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\30\44\25\0\1\362"+
    "\112\0\5\363\75\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\14\24\1\206\13\24\72\0"+
    "\1\276\35\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\1\364\27\24\14\0\1\365\1\0"+
    "\1\44\4\0\2\44\1\0\5\44\1\366\1\0\1\45"+
    "\22\44\2\0\30\24\14\0\1\367\1\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\30\24"+
    "\16\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\20\24\1\370\7\24\16\0\1\44\4\0"+
    "\2\44\1\0\5\44\2\0\1\45\22\44\2\0\16\24"+
    "\1\371\11\24\14\0\1\372\1\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\30\24\37\0"+
    "\1\373\70\0\1\44\4\0\2\44\1\0\5\44\1\0"+
    "\1\274\1\45\22\44\2\0\30\24\72\0\1\374\26\0"+
    "\2\41\1\0\2\41\1\375\1\42\103\41\12\0\1\376"+
    "\106\0\1\44\4\0\2\44\1\0\5\377\2\0\1\45"+
    "\22\44\2\0\30\44\16\0\1\44\4\0\2\44\1\0"+
    "\3\u0100\2\44\2\0\1\45\22\44\2\0\30\44\26\0"+
    "\3\341\77\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\22\24\1\u0101\5\24\14\0\1\365"+
    "\16\0\1\366\134\0\1\u0102\51\0\1\44\4\0\2\44"+
    "\1\0\5\44\2\0\1\45\22\44\2\0\20\24\1\206"+
    "\7\24\16\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\1\u0103\27\24\50\0\1\u0104\123\0"+
    "\1\u0105\113\0\1\u0106\34\0\2\41\1\0\3\41\1\42"+
    "\10\41\5\u0107\66\41\14\0\1\u0108\104\0\1\44\4\0"+
    "\2\44\1\0\5\u0100\2\0\1\45\22\44\2\0\30\44"+
    "\16\0\1\44\4\0\2\44\1\0\5\u0109\2\0\1\45"+
    "\22\44\2\0\30\44\16\0\1\44\4\0\2\44\1\0"+
    "\5\44\2\0\1\45\22\44\2\0\15\24\1\u010a\12\24"+
    "\76\0\1\u010b\31\0\1\44\4\0\2\44\1\0\5\44"+
    "\2\0\1\45\22\44\2\0\14\24\1\u010c\13\24\102\0"+
    "\1\u010d\102\0\1\u010e\115\0\1\u010f\21\0\2\41\1\0"+
    "\3\41\1\42\10\41\5\u0110\66\41\12\0\1\u0111\162\0"+
    "\1\u0112\35\0\1\44\4\0\2\44\1\0\5\44\2\0"+
    "\1\45\22\44\2\0\22\24\1\u0113\5\24\77\0\1\u0114"+
    "\111\0\1\u0115\115\0\1\u0116\15\0\2\41\1\0\3\41"+
    "\1\42\10\41\5\u0117\66\41\14\0\1\u0118\153\0\1\u010e"+
    "\42\0\1\44\4\0\2\44\1\0\5\44\2\0\1\45"+
    "\22\44\2\0\4\24\1\u0119\23\24\14\0\1\u0114\16\0"+
    "\1\u011a\161\0\1\274\22\0\1\u011b\104\0\2\41\1\0"+
    "\3\41\1\42\10\41\5\u011c\66\41\12\0\1\u011d\106\0"+
    "\1\44\4\0\2\44\1\0\5\44\1\u011e\1\0\1\45"+
    "\22\44\2\0\30\24\52\0\1\u011f\46\0\2\41\1\0"+
    "\3\41\1\u0120\103\41\14\0\1\u0121\150\0\1\u0122\50\0"+
    "\1\u0123\172\0\1\u0124\32\0\1\u0125\172\0\1\u0126\26\0"+
    "\1\u0127\162\0\1\u0128\42\0\1\u0129\153\0\1\u012a\45\0"+
    "\1\u012b\167\0\1\u012c\35\0\1\u012d\171\0\1\u012e\41\0"+
    "\1\u012f\65\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[20646];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\7\1\1\11\5\1\1\11\16\1\2\11"+
    "\1\0\1\11\5\0\22\1\1\0\5\1\1\0\3\1"+
    "\2\0\1\11\3\0\1\1\2\0\23\1\1\0\2\1"+
    "\1\0\4\1\1\0\3\1\15\0\1\1\2\0\22\1"+
    "\1\0\1\1\1\0\2\1\1\0\4\1\1\0\2\1"+
    "\1\0\1\1\16\0\1\1\1\11\1\0\3\1\1\0"+
    "\6\1\1\0\3\1\1\11\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\3\1\7\0\1\1\1\0\5\1\1\11"+
    "\2\1\1\0\1\1\1\0\1\1\7\0\1\1\1\0"+
    "\7\1\1\0\1\1\6\0\1\11\1\1\1\0\1\11"+
    "\1\0\2\1\7\0\1\1\1\0\1\1\5\0\2\1"+
    "\1\0\1\1\6\0\1\1\5\0\1\1\1\11\3\0"+
    "\1\11\1\0\1\11\14\0\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[303];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("CARACTER ILEGAL: '" + yytext() + 
        "' en línea " + (yyline + 1) + ", columna " + (yycolumn + 1));
            }
          // fall through
          case 26: break;
          case 2:
            { 
            }
          // fall through
          case 27: break;
          case 3:
            { //System.out.println("TOKEN COMA: " + yytext()); 
    return symbol(sym.COMA);
            }
          // fall through
          case 28: break;
          case 4:
            { //System.out.println("TOKEN GUION: " + yytext()); 
    return symbol(sym.GUION);
            }
          // fall through
          case 29: break;
          case 5:
            { Integer numero = Integer.parseInt(yytext());
    //System.out.println("TOKEN NUMERO: " + numero);
    return symbol(sym.NUMERO, numero);
            }
          // fall through
          case 30: break;
          case 6:
            { //System.out.println("TOKEN DOSPUNTOS: " + yytext()); 
    return symbol(sym.DOSPUNTOS);
            }
          // fall through
          case 31: break;
          case 7:
            { //System.out.println("TOKEN NOMBRE: " + yytext());
    return symbol(sym.NOMBRE, yytext());
            }
          // fall through
          case 32: break;
          case 8:
            { //System.out.println("TOKEN CORCHETE_IZQ: " + yytext()); 
    return symbol(sym.CORCHETE_IZQ);
            }
          // fall through
          case 33: break;
          case 9:
            { //System.out.println("TOKEN CORCHETE_DER: " + yytext()); 
    return symbol(sym.CORCHETE_DER);
            }
          // fall through
          case 34: break;
          case 10:
            { //System.out.println("TOKEN QSTRING: " + yytext());
    return symbol(sym.QSTRING, yytext());
            }
          // fall through
          case 35: break;
          case 11:
            { //System.out.println("TOKEN MARCA: " + yytext()); 
    return symbol(sym.MARCA);
            }
          // fall through
          case 36: break;
          case 12:
            { //System.out.println("TOKEN EMAIL: " + yytext());
    return symbol(sym.EMAIL, yytext());
            }
          // fall through
          case 37: break;
          case 13:
            { //System.out.println("TOKEN HORA: " + yytext());
    return symbol(sym.HORA, yytext());
            }
          // fall through
          case 38: break;
          case 14:
            { //System.out.println("TOKEN EQUIPO: " + yytext());
    return symbol(sym.EQUIPO, yytext());
            }
          // fall through
          case 39: break;
          case 15:
            { //System.out.println("TOKEN SERIE: " + yytext()); 
    return symbol(sym.SERIE);
            }
          // fall through
          case 40: break;
          case 16:
            { //System.out.println("TOKEN JUEGO: " + yytext()); 
    return symbol(sym.JUEGO);
            }
          // fall through
          case 41: break;
          case 17:
            { //System.out.println("TOKEN FIXTURE: " + yytext()); 
    return symbol(sym.FIXTURE);
            }
          // fall through
          case 42: break;
          case 18:
            { //System.out.println("TOKEN FECHA: " + yytext());
    return symbol(sym.FECHA, yytext());
            }
          // fall through
          case 43: break;
          case 19:
            { //System.out.println("TOKEN PRE_EQUIPOS: " + yytext()); 
    return symbol(sym.PRE_EQUIPOS);
            }
          // fall through
          case 44: break;
          case 20:
            { //System.out.println("TOKEN CAMPEONATO: " + yytext()); 
    return symbol(sym.CAMPEONATO);
            }
          // fall through
          case 45: break;
          case 21:
            { //System.out.println("TOKEN NRO_PARTIDO: " + yytext()); 
    return symbol(sym.NRO_PARTIDO);
            }
          // fall through
          case 46: break;
          case 22:
            { //System.out.println("TOKEN PRE_PARTICIPANTE: " + yytext()); 
    return symbol(sym.PRE_PARTICIPANTE);
            }
          // fall through
          case 47: break;
          case 23:
            { //System.out.println("TOKEN TORNEO: " + yytext());
    return symbol(sym.TORNEO, yytext());
            }
          // fall through
          case 48: break;
          case 24:
            { //System.out.println("TOKEN SEPARADOR: " + yytext()); 
    return symbol(sym.SEPARADOR);
            }
          // fall through
          case 49: break;
          case 25:
            { //System.out.println("TOKEN PRONOSTICOS: " + yytext()); 
    return symbol(sym.PRONOSTICOS);
            }
          // fall through
          case 50: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
