// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: pronostico.flex

import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\2\22\0\1\5"+
    "\1\0\1\6\2\0\1\7\2\0\1\10\1\11\1\12"+
    "\1\7\1\13\1\14\1\15\1\16\2\17\2\20\6\21"+
    "\1\22\1\23\4\0\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\2\33\1\34\1\35\2\33\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\33\1\45\2\33"+
    "\1\46\2\33\1\47\1\0\1\50\1\0\1\7\1\0"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\56\1\63\1\64\1\65\1\66\1\67"+
    "\1\70\1\71\1\72\1\73\1\74\1\75\1\56\1\76"+
    "\1\77\1\100\1\0\1\101\10\0\1\3\133\0\1\102"+
    "\7\0\1\103\3\0\1\104\3\0\1\105\1\0\1\106"+
    "\6\0\1\107\u012d\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\3\2\4\1\1\3\1\4\2\5\1\6"+
    "\16\7\1\10\1\11\1\0\1\12\5\0\2\5\17\7"+
    "\1\0\5\7\1\0\3\7\2\0\1\13\3\0\1\5"+
    "\1\0\23\7\1\0\2\7\1\0\4\7\1\0\3\7"+
    "\15\0\1\5\1\0\22\7\1\0\1\7\1\0\2\7"+
    "\1\0\4\7\1\0\2\7\1\0\1\14\16\0\1\5"+
    "\1\0\3\7\1\0\3\7\1\15\2\7\1\0\3\7"+
    "\1\15\1\7\1\0\1\7\1\0\1\7\1\0\1\16"+
    "\2\7\7\0\1\7\1\0\5\7\1\17\2\7\1\0"+
    "\1\7\1\0\1\7\7\0\1\7\1\0\3\7\1\20"+
    "\3\7\1\0\1\7\6\0\1\21\1\7\1\0\1\22"+
    "\1\0\2\7\7\0\1\7\1\0\1\7\5\0\1\21"+
    "\1\23\1\0\1\7\6\0\1\7\5\0\1\7\1\24"+
    "\3\0\1\25\1\0\1\26\14\0\1\27\1\0\1\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[297];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\110\0\220\0\330\0\u0120\0\u0168\0\u01b0\0\u01f8"+
    "\0\u0240\0\110\0\u01b0\0\u0288\0\u02d0\0\110\0\u0318\0\u0360"+
    "\0\u03a8\0\u03f0\0\u0438\0\u0480\0\u04c8\0\u0510\0\u0558\0\u05a0"+
    "\0\u05e8\0\u0630\0\u0678\0\u06c0\0\110\0\110\0\u0708\0\110"+
    "\0\u0750\0\u01b0\0\u0798\0\u07e0\0\u0828\0\u0870\0\u08b8\0\u0900"+
    "\0\u0948\0\u0990\0\u09d8\0\u0a20\0\u0a68\0\u0ab0\0\u0af8\0\u0b40"+
    "\0\u0b88\0\u0bd0\0\u0c18\0\u0c60\0\u0ca8\0\u0cf0\0\u0d38\0\u0d80"+
    "\0\u0dc8\0\u0e10\0\u0e58\0\u0ea0\0\u0ee8\0\u0f30\0\u0f78\0\u0fc0"+
    "\0\u1008\0\u1050\0\110\0\u1098\0\u10e0\0\u1128\0\u1170\0\u11b8"+
    "\0\u1200\0\u1248\0\u1290\0\u12d8\0\u1320\0\u1368\0\u13b0\0\u13f8"+
    "\0\u1440\0\u1488\0\u14d0\0\u1518\0\u1560\0\u15a8\0\u15f0\0\u1638"+
    "\0\u1680\0\u16c8\0\u1710\0\u1758\0\u17a0\0\u17e8\0\u1830\0\u1878"+
    "\0\u18c0\0\u1908\0\u1950\0\u1998\0\u19e0\0\u1a28\0\u1a70\0\u1ab8"+
    "\0\u1b00\0\u1b48\0\u1b90\0\u1bd8\0\u1c20\0\u1c68\0\u1cb0\0\u1cf8"+
    "\0\u1d40\0\u1d88\0\u1dd0\0\u1e18\0\u1e60\0\u1ea8\0\u1ef0\0\u1f38"+
    "\0\u1f80\0\u1fc8\0\u2010\0\u2058\0\u20a0\0\u20e8\0\u2130\0\u2178"+
    "\0\u21c0\0\u2208\0\u2250\0\u2298\0\u22e0\0\u2328\0\u2370\0\u23b8"+
    "\0\u2400\0\u2448\0\u2490\0\u24d8\0\u2520\0\u2568\0\u25b0\0\u25f8"+
    "\0\u2640\0\u2688\0\u26d0\0\u2718\0\u2760\0\u27a8\0\u1b00\0\u27f0"+
    "\0\u2838\0\u2880\0\u28c8\0\u2910\0\u2958\0\u29a0\0\u29e8\0\u2a30"+
    "\0\u2a78\0\u2ac0\0\u2b08\0\u2b50\0\u2b98\0\u2be0\0\u2c28\0\u2c70"+
    "\0\u2cb8\0\u2d00\0\u2d48\0\u2d90\0\u2dd8\0\u2e20\0\u03f0\0\u2e68"+
    "\0\u2eb0\0\u2ef8\0\u2f40\0\u2f88\0\u2fd0\0\110\0\u3018\0\u3060"+
    "\0\u30a8\0\u30f0\0\u3138\0\u3180\0\u01b0\0\u31c8\0\u3210\0\u3258"+
    "\0\u32a0\0\u32e8\0\u3330\0\u3378\0\u33c0\0\u3408\0\u3450\0\u3498"+
    "\0\u34e0\0\u3528\0\u3570\0\u35b8\0\u3600\0\110\0\u3648\0\u3690"+
    "\0\u36d8\0\u3720\0\u3768\0\u37b0\0\u37f8\0\u3840\0\u3888\0\u38d0"+
    "\0\u3918\0\u3960\0\u39a8\0\u39f0\0\u3a38\0\u3a80\0\u3ac8\0\u3b10"+
    "\0\u03f0\0\u3b58\0\u3ba0\0\u3be8\0\u3c30\0\u3c78\0\u3cc0\0\u3d08"+
    "\0\u3d50\0\u3d98\0\u3de0\0\u3e28\0\110\0\u3e70\0\u3eb8\0\110"+
    "\0\u3f00\0\u3f48\0\u3f90\0\u3fd8\0\u4020\0\u4068\0\u40b0\0\u40f8"+
    "\0\u4140\0\u4188\0\u41d0\0\u4218\0\u4260\0\u42a8\0\u42f0\0\u4338"+
    "\0\u4380\0\u43c8\0\u01b0\0\u03f0\0\u4410\0\u4458\0\u44a0\0\u44e8"+
    "\0\u4530\0\u4578\0\u45c0\0\u4608\0\u4650\0\u4698\0\u46e0\0\u4728"+
    "\0\u4770\0\u47b8\0\u4800\0\110\0\u4848\0\u4890\0\u48d8\0\110"+
    "\0\u4920\0\110\0\u4968\0\u49b0\0\u49f8\0\u4a40\0\u4a88\0\u4ad0"+
    "\0\u4b18\0\u4b60\0\u4ba8\0\u4bf0\0\u4c38\0\u4c80\0\110\0\u4cc8"+
    "\0\110";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[297];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\5\1\3\1\6\1\7"+
    "\1\10\1\2\1\11\1\12\1\13\1\7\1\2\2\14"+
    "\1\15\1\16\2\2\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\22\1\25\1\26\1\27\1\30\1\22\1\31"+
    "\1\32\1\22\1\33\1\34\1\22\1\35\1\36\30\7"+
    "\7\2\111\0\1\3\1\4\1\0\1\5\1\3\103\0"+
    "\2\4\2\0\1\4\103\0\1\5\2\0\2\5\102\0"+
    "\2\37\1\0\3\37\1\40\27\37\1\41\51\37\7\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\30\42\55\0\1\44\55\0\1\45\102\0\1\42"+
    "\4\0\2\42\1\0\3\46\2\0\1\43\22\42\2\0"+
    "\30\42\16\0\1\42\4\0\2\42\1\0\3\47\2\0"+
    "\1\43\22\42\2\0\30\42\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\12\22\1\50"+
    "\5\22\1\51\2\22\1\52\4\22\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\20\22"+
    "\1\53\7\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\1\54\6\22\1\55\5\22"+
    "\1\56\12\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\30\22\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\17\22"+
    "\1\57\1\22\1\60\6\22\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\10\22\1\61"+
    "\7\22\1\62\7\22\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\14\22\1\63\5\22"+
    "\1\64\5\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\1\65\22\22\1\66\4\22"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\30\22\2\0\1\67\13\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\10\22"+
    "\1\70\17\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\1\71\14\22\1\72\2\22"+
    "\1\73\7\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\1\74\27\22\16\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\4\42\1\75"+
    "\15\42\2\0\4\22\1\76\16\22\1\77\4\22\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\20\22\1\100\7\22\7\0\2\37\1\0\3\37"+
    "\1\40\103\37\1\0\3\37\1\40\65\37\1\101\13\37"+
    "\25\0\22\102\2\0\30\102\20\0\1\103\110\0\1\104"+
    "\104\0\1\42\4\0\1\105\1\42\1\106\3\107\2\0"+
    "\1\43\22\42\2\0\30\42\1\110\15\0\1\42\4\0"+
    "\2\42\1\0\3\107\2\0\1\43\22\42\2\0\30\42"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\4\22\1\111\23\22\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\6\22"+
    "\1\112\21\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\21\22\1\113\6\22\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\1\114\27\22\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\1\22\1\115\11\22"+
    "\1\116\1\117\13\22\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\10\22\1\120\17\22"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\12\22\1\121\5\22\1\122\7\22\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\23\22\1\123\4\22\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\16\22\1\124"+
    "\3\22\1\125\5\22\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\25\22\1\126\2\22"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\1\127\27\22\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\6\22\1\130"+
    "\21\22\16\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\1\131\27\22\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\16\22"+
    "\1\132\11\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\4\22\1\133\23\22\105\0"+
    "\1\134\20\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\6\22\1\135\21\22\16\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\20\22\1\136\7\22\3\0\1\137\12\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\12\22"+
    "\1\140\5\22\1\141\7\22\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\15\22\1\142"+
    "\12\22\16\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\22\22\1\143\5\22\16\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\16\42\1\144"+
    "\3\42\2\0\30\42\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\14\22\1\145\13\22"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\10\22\1\146\17\22\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\23\22"+
    "\1\147\4\22\7\0\2\37\1\0\3\37\1\40\56\37"+
    "\1\150\22\37\15\0\1\151\7\0\22\102\2\0\30\102"+
    "\23\0\1\152\102\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\1\153\2\42\1\154\1\155\1\156\2\42"+
    "\1\157\1\160\1\161\1\162\3\42\1\163\2\42\2\0"+
    "\30\42\26\0\1\164\77\0\1\42\4\0\2\42\1\0"+
    "\3\165\2\0\1\43\22\42\2\0\30\42\26\0\1\166"+
    "\77\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\13\22\1\167\14\22\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\4\22"+
    "\1\170\23\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\22\22\1\171\5\22\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\21\22\1\172\6\22\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\15\22\1\173"+
    "\12\22\16\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\4\22\1\174\11\22\1\175\11\22"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\1\176\27\22\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\12\22\1\177"+
    "\15\22\16\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\15\22\1\200\12\22\16\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\4\22\1\201\23\22\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\10\22\1\202\17\22"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\1\203\27\22\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\1\204\27\22"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\22\22\1\205\5\22\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\14\22"+
    "\1\206\13\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\12\22\1\207\15\22\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\12\22\1\210\15\22\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\30\22\5\0"+
    "\1\211\10\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\6\22\1\212\21\22\70\0\1\213"+
    "\35\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\4\22\1\214\23\22\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\22\22"+
    "\1\215\5\22\101\0\1\216\24\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\15\22\1\217"+
    "\12\22\16\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\22\22\1\220\5\22\16\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\14\22\1\221\13\22\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\1\222\27\22\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\7\42"+
    "\1\223\12\42\2\0\30\42\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\4\22\1\224"+
    "\23\22\16\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\27\22\1\201\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\6\22"+
    "\1\225\21\22\7\0\2\37\1\0\3\37\1\40\45\37"+
    "\1\226\33\37\25\0\22\227\2\0\30\227\21\0\1\230"+
    "\104\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\1\42\1\231\4\42\1\232\21\42\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\10\42\1\233\17\42\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\14\42\1\234"+
    "\13\42\16\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\4\42\1\235\23\42\16\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\23\42\1\236\4\42\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\1\237\27\42\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\15\42\1\240\12\42\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\2\42\1\241"+
    "\25\42\16\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\4\42\1\242\23\42\26\0\3\243"+
    "\75\0\1\42\4\0\1\244\1\42\1\245\3\246\2\0"+
    "\1\43\22\42\2\0\30\42\26\0\3\247\75\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\1\250\27\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\14\22\1\251\13\22\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\20\22\1\64\7\22\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\10\22\1\252"+
    "\17\22\14\0\1\253\1\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\30\22\16\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\20\22\1\254\7\22\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\4\22\1\255\23\22"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\3\22\1\256\24\22\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\4\22"+
    "\1\257\23\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\13\22\1\260\14\22\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\1\257\27\22\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\16\22\1\261\11\22"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\30\22\4\0\1\262\11\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\3\22"+
    "\1\263\24\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\23\22\1\264\4\22\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\2\22\1\210\25\22\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\1\265\27\22"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\10\22\1\201\17\22\74\0\1\266\31\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\15\22\1\267\12\22\62\0\1\270\43\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\20\22\1\210\7\22\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\10\22\1\271\17\22"+
    "\64\0\1\272\41\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\14\22\1\273\13\22\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\23\22\1\224\4\22\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\30\22\5\0"+
    "\1\274\10\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\20\22\1\257\7\22\16\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\4\42\1\275"+
    "\15\42\2\0\30\42\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\6\22\1\276\21\22"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\23\22\1\277\4\22\7\0\2\37\1\0"+
    "\3\37\1\40\52\37\1\300\26\37\14\0\1\301\102\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\20\42\1\302\7\42\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\15\42\1\302"+
    "\12\42\16\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\2\42\1\302\25\42\16\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\4\42\1\302\23\42\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\1\42\1\302\26\42"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\12\42\1\302\1\42\1\302\13\42\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\20\42\1\302\5\42\1\302\1\42\16\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\24\42\1\302\3\42\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\22\42\1\302\5\42"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\16\42\1\302\11\42\25\0\1\303\100\0"+
    "\1\42\4\0\2\42\1\0\1\304\2\42\2\0\1\43"+
    "\22\42\2\0\30\42\26\0\1\305\77\0\1\42\4\0"+
    "\2\42\1\0\3\246\2\0\1\43\22\42\2\0\30\42"+
    "\110\0\1\306\15\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\14\22\1\210\13\22\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\22\22\1\307\5\22\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\12\22\1\257"+
    "\15\22\41\0\1\310\64\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\30\22\6\0\1\211"+
    "\7\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\15\22\1\311\12\22\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\30\22"+
    "\1\0\1\266\14\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\1\22\1\210\26\22\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\15\22\1\312\12\22\60\0\1\266\45\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\15\22\1\313\12\22\16\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\20\22\1\314\7\22"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\22\22\1\315\5\22\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\1\316\1\0\1\43\22\42\2\0"+
    "\30\22\75\0\1\266\30\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\2\22\1\317\1\320"+
    "\24\22\101\0\1\321\24\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\10\22\1\322\17\22"+
    "\101\0\1\323\24\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\1\252\27\22\16\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\1\324\27\22\7\0\2\37\1\0\3\37\1\40\42\37"+
    "\1\325\36\37\12\0\1\326\104\0\1\42\4\0\1\327"+
    "\1\42\1\0\3\42\2\0\1\43\22\42\2\0\30\42"+
    "\26\0\3\330\75\0\1\42\4\0\2\42\1\0\3\331"+
    "\2\0\1\43\22\42\2\0\30\42\26\0\3\332\105\0"+
    "\3\333\75\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\10\22\1\334\17\22\100\0\1\335"+
    "\25\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\14\22\1\336\13\22\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\21\22"+
    "\1\337\6\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\21\22\1\340\6\22\16\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\4\22\1\341\23\22\16\0\1\42\4\0\2\42"+
    "\1\0\3\42\2\0\1\43\22\42\2\0\4\22\1\342"+
    "\23\22\16\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\10\22\1\343\17\22\16\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\15\22\1\344\12\22\14\0\1\345\111\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\1\346"+
    "\27\22\102\0\1\347\23\0\1\42\4\0\2\42\1\0"+
    "\3\42\2\0\1\43\22\42\2\0\26\22\1\257\1\22"+
    "\7\0\2\37\1\0\3\37\1\40\54\37\1\350\24\37"+
    "\14\0\1\351\102\0\1\42\4\0\2\42\1\0\3\352"+
    "\2\0\1\43\22\42\2\0\30\42\26\0\3\306\75\0"+
    "\1\42\4\0\1\353\1\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\30\42\25\0\1\354\110\0\3\355\75\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\14\22\1\201\13\22\70\0\1\270\35\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\1\356\27\22\14\0\1\357\1\0\1\42\4\0\2\42"+
    "\1\0\3\42\1\360\1\0\1\43\22\42\2\0\30\22"+
    "\14\0\1\361\1\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\30\22\16\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\20\22"+
    "\1\362\7\22\16\0\1\42\4\0\2\42\1\0\3\42"+
    "\2\0\1\43\22\42\2\0\16\22\1\363\11\22\14\0"+
    "\1\364\1\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\30\22\35\0\1\365\70\0\1\42"+
    "\4\0\2\42\1\0\3\42\1\0\1\266\1\43\22\42"+
    "\2\0\30\22\70\0\1\366\26\0\2\37\1\0\2\37"+
    "\1\367\1\40\101\37\12\0\1\370\104\0\1\42\4\0"+
    "\2\42\1\0\3\371\2\0\1\43\22\42\2\0\30\42"+
    "\16\0\1\42\4\0\2\42\1\0\2\372\1\42\2\0"+
    "\1\43\22\42\2\0\30\42\26\0\2\333\76\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\22\22\1\373\5\22\14\0\1\357\14\0\1\360\132\0"+
    "\1\374\51\0\1\42\4\0\2\42\1\0\3\42\2\0"+
    "\1\43\22\42\2\0\20\22\1\201\7\22\16\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\1\375\27\22\46\0\1\376\121\0\1\377\111\0\1\u0100"+
    "\34\0\2\37\1\0\3\37\1\40\10\37\3\u0101\66\37"+
    "\14\0\1\u0102\102\0\1\42\4\0\2\42\1\0\3\372"+
    "\2\0\1\43\22\42\2\0\30\42\16\0\1\42\4\0"+
    "\2\42\1\0\3\u0103\2\0\1\43\22\42\2\0\30\42"+
    "\16\0\1\42\4\0\2\42\1\0\3\42\2\0\1\43"+
    "\22\42\2\0\15\22\1\u0104\12\22\74\0\1\u0105\31\0"+
    "\1\42\4\0\2\42\1\0\3\42\2\0\1\43\22\42"+
    "\2\0\14\22\1\u0106\13\22\100\0\1\u0107\100\0\1\u0108"+
    "\113\0\1\u0109\21\0\2\37\1\0\3\37\1\40\10\37"+
    "\3\u010a\66\37\12\0\1\u010b\156\0\1\u010c\35\0\1\42"+
    "\4\0\2\42\1\0\3\42\2\0\1\43\22\42\2\0"+
    "\22\22\1\u010d\5\22\75\0\1\u010e\107\0\1\u010f\113\0"+
    "\1\u0110\15\0\2\37\1\0\3\37\1\40\10\37\3\u0111"+
    "\66\37\14\0\1\u0112\147\0\1\u0108\42\0\1\42\4\0"+
    "\2\42\1\0\3\42\2\0\1\43\22\42\2\0\4\22"+
    "\1\u0113\23\22\14\0\1\u010e\14\0\1\u0114\157\0\1\266"+
    "\22\0\1\u0115\102\0\2\37\1\0\3\37\1\40\10\37"+
    "\3\u0116\66\37\12\0\1\u0117\104\0\1\42\4\0\2\42"+
    "\1\0\3\42\1\u0118\1\0\1\43\22\42\2\0\30\22"+
    "\50\0\1\u0119\46\0\2\37\1\0\3\37\1\u011a\101\37"+
    "\14\0\1\u011b\144\0\1\u011c\50\0\1\u011d\166\0\1\u011e"+
    "\32\0\1\u011f\166\0\1\u0120\26\0\1\u0121\156\0\1\u0122"+
    "\42\0\1\u0123\147\0\1\u0124\45\0\1\u0125\163\0\1\u0126"+
    "\35\0\1\u0127\165\0\1\u0128\37\0\1\u0129\65\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[19728];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\7\1\1\11\3\1\1\11\16\1\2\11"+
    "\1\0\1\11\5\0\21\1\1\0\5\1\1\0\3\1"+
    "\2\0\1\11\3\0\1\1\1\0\23\1\1\0\2\1"+
    "\1\0\4\1\1\0\3\1\15\0\1\1\1\0\22\1"+
    "\1\0\1\1\1\0\2\1\1\0\4\1\1\0\2\1"+
    "\1\0\1\1\16\0\1\1\1\0\3\1\1\0\6\1"+
    "\1\0\3\1\1\11\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\3\1\7\0\1\1\1\0\5\1\1\11\2\1"+
    "\1\0\1\1\1\0\1\1\7\0\1\1\1\0\7\1"+
    "\1\0\1\1\6\0\1\11\1\1\1\0\1\11\1\0"+
    "\2\1\7\0\1\1\1\0\1\1\5\0\2\1\1\0"+
    "\1\1\6\0\1\1\5\0\1\1\1\11\3\0\1\11"+
    "\1\0\1\11\14\0\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[297];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("CARACTER ILEGAL: '" + yytext() + 
        "' en línea " + (yyline + 1) + ", columna " + (yycolumn + 1));
            }
          // fall through
          case 25: break;
          case 2:
            { 
            }
          // fall through
          case 26: break;
          case 3:
            { //System.out.println("TOKEN COMA: " + yytext()); 
    return symbol(sym.COMA);
            }
          // fall through
          case 27: break;
          case 4:
            { //System.out.println("TOKEN GUION: " + yytext()); 
    return symbol(sym.GUION);
            }
          // fall through
          case 28: break;
          case 5:
            { Integer numero = Integer.parseInt(yytext());
    //System.out.println("TOKEN NUMERO: " + numero);
    return symbol(sym.NUMERO, numero);
            }
          // fall through
          case 29: break;
          case 6:
            { //System.out.println("TOKEN DOSPUNTOS: " + yytext()); 
    return symbol(sym.DOSPUNTOS);
            }
          // fall through
          case 30: break;
          case 7:
            { //System.out.println("TOKEN NOMBRE: " + yytext());
    return symbol(sym.NOMBRE, yytext());
            }
          // fall through
          case 31: break;
          case 8:
            { //System.out.println("TOKEN CORCHETE_IZQ: " + yytext()); 
    return symbol(sym.CORCHETE_IZQ);
            }
          // fall through
          case 32: break;
          case 9:
            { //System.out.println("TOKEN CORCHETE_DER: " + yytext()); 
    return symbol(sym.CORCHETE_DER);
            }
          // fall through
          case 33: break;
          case 10:
            { //System.out.println("TOKEN QSTRING: " + yytext());
    return symbol(sym.QSTRING, yytext());
            }
          // fall through
          case 34: break;
          case 11:
            { //System.out.println("TOKEN MARCA: " + yytext()); 
    return symbol(sym.MARCA);
            }
          // fall through
          case 35: break;
          case 12:
            { //System.out.println("TOKEN EMAIL: " + yytext());
    return symbol(sym.EMAIL, yytext());
            }
          // fall through
          case 36: break;
          case 13:
            { //System.out.println("TOKEN EQUIPO: " + yytext());
    return symbol(sym.EQUIPO, yytext());
            }
          // fall through
          case 37: break;
          case 14:
            { //System.out.println("TOKEN SERIE: " + yytext()); 
    return symbol(sym.SERIE);
            }
          // fall through
          case 38: break;
          case 15:
            { //System.out.println("TOKEN JUEGO: " + yytext()); 
    return symbol(sym.JUEGO);
            }
          // fall through
          case 39: break;
          case 16:
            { //System.out.println("TOKEN FIXTURE: " + yytext()); 
    return symbol(sym.FIXTURE);
            }
          // fall through
          case 40: break;
          case 17:
            { //System.out.println("TOKEN FECHA: " + yytext());
    return symbol(sym.FECHA, yytext());
            }
          // fall through
          case 41: break;
          case 18:
            { //System.out.println("TOKEN PRE_EQUIPOS: " + yytext()); 
    return symbol(sym.PRE_EQUIPOS);
            }
          // fall through
          case 42: break;
          case 19:
            { //System.out.println("TOKEN CAMPEONATO: " + yytext()); 
    return symbol(sym.CAMPEONATO);
            }
          // fall through
          case 43: break;
          case 20:
            { //System.out.println("TOKEN NRO_PARTIDO: " + yytext()); 
    return symbol(sym.NRO_PARTIDO);
            }
          // fall through
          case 44: break;
          case 21:
            { //System.out.println("TOKEN PRE_PARTICIPANTE: " + yytext()); 
    return symbol(sym.PRE_PARTICIPANTE);
            }
          // fall through
          case 45: break;
          case 22:
            { //System.out.println("TOKEN TORNEO: " + yytext());
    return symbol(sym.TORNEO, yytext());
            }
          // fall through
          case 46: break;
          case 23:
            { //System.out.println("TOKEN SEPARADOR: " + yytext()); 
    return symbol(sym.SEPARADOR);
            }
          // fall through
          case 47: break;
          case 24:
            { //System.out.println("TOKEN PRONOSTICOS: " + yytext()); 
    return symbol(sym.PRONOSTICOS);
            }
          // fall through
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
